# Generated by Django 4.2.11 on 2024-04-25 14:28

from django.db import migrations, models
import trading.models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_buy_or_sell',
            field=models.IntegerField(choices=[(1, 'BUY'), (-1, 'SELL')], default=trading.models.OrderType['BUY']),
        ),
    ]
