# Generated by Django 4.2.11 on 2024-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_order_is_buy_or_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_buy_or_sell',
            field=models.IntegerField(choices=[(1, 'BUY'), (-1, 'SELL')], default=1),
        ),
    ]
